
```{r}
library(RuralGrocery)
```

# Market Size Testing
```{r}
# Testing variables for all county cities and non-county cities in the market area

## County square mileage
county_sqmiles <- 373.3

## County total population
county_pop <- 7659

metro <- 150

## County cities population list
county_towns <- list(Town2 = 200,
                      Town3 = 300,
                      Town4 = 700,
                      Town5 = 150)

## Non-County cities population list
non_county_towns <- list(town1 = 250)

county_market_cities <- list(town1 = 150)

# Shopper Count Percentages
## Metro
m_prime_pct <- 50
m_second_pct <- 40
m_rare_pct <- 10

## Rural
r_prime_pct <- 30
r_second_pct <- 50
r_rare_pct <- 20

## Town
t_prime_pct <- 30
t_second_pct <- 50
t_rare_pct <- 20

```

```{r}
market_pct <- Quadrant_Area(12,13,25,9) # market_total_area should be 200

county_pct <- County_Pct(county_area = county_sqmiles, 
                         market_total_area = market_pct$market_total_area) # Should equal to .536

populations <- Market_Populations(county_pct = county_pct,
                                  county_pop = county_pop,
                                  metro_pop = metro, 
                                  county_cities = county_towns, 
                                  non_county_cities = non_county_towns,
                                  county_market_cities = county_market_cities) 

Shoppers_List <- Shopper_Populations(populations_list = populations, 
                                     
                                     metro_primary_pct = m_prime_pct, 
                                     metro_secondary_pct = m_second_pct, 
                                     metro_rare_pct = m_rare_pct,
                                     
                                     town_primary_pct = t_prime_pct, 
                                     town_secondary_pct = t_second_pct, 
                                     town_rare_pct = t_rare_pct,
                                     
                                     rural_primary_pct = r_prime_pct, 
                                     rural_secondary_pct = r_second_pct, 
                                     rural_rare_pct = r_rare_pct)
```

```{r}
populations # These are the values that should come out
```

# Estimated Revenue Testing

```{r}
primary_pct = 60
secondary_pct = 25
rare_pct = 5
```


```{r}
Adjusted_List <- Adj_Per_Cap_Spend(Cumulative_Price_Inc = 5, 
                                   State_Index = 95.8)

Total_Rev_List <- Total_Revenue(Adjusted_Per_Capita = Adjusted_List$Adjusted_CPI_State,
                                Primary_Pct = primary_pct,
                                Secondary_Pct = secondary_pct,
                                Rare_Pct = rare_pct, 
                                Primary_Shoppers = Shoppers_List$primary_total,
                                Secondary_Shoppers = Shoppers_List$secondary_total,
                                Rare_Shoppers = Shoppers_List$rare_total)
```

```{r}
Adjusted_List # Expected Values to Return
Total_Rev_List
```

# Expenses and Pre-tax Profit Calculation
## Data Frames for Input Values
```{r}
depreciation <-
    data.frame(
      id = c(
        "building_remodeling",
        "leasehold_improvements",
        "parking_lot_improvements",
        "shelving",
        "equipments",
        "vehicle",
        "display_cases",
        "refrigeration",
        "freezers",
        "meat_cutting_equipment",
        "amortization_start_up_cost",
        "miscellaneous_1",
        "miscellaneous_2",
        "miscellaneous_3"
      ),
      life = c(39, 15, 15, 15, 5, 5, 15, 15, 15, 12, 15, 0, 0, 0),
      cost = c(3000, 1000, 650, 500, 500, 750, 800, 500, 550, 625, 800, 0, 0, 0),
      annual_cost = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
    )

rent <-
    data.frame(
      id = c("building_rent", "other_rent1", "other_rent2"),
      rent = c(2500, 500, 0),
      annual_cost = c(0, 0, 0)
    )

interest <- data.frame(
    id = c("loan_1", "loan_2", "loan_3"),
    loan = c(5000, 2000, 600),
    interest = c(3, 3, 0.5),
    calculated_interest = c(0, 0, 0)
  )


expenses <- data.frame(
  id = c("gross_margin", # Rev * Pct (default = [22, 24, 26, or 28])
         "salaries", # Rev * Pct (default = 9)
         "other_operating_expense", # Rev * Pct (default = 10.88)
         "other_income", # Rev * Pct (Default = 1) [this value REDUCES expense]
         "officer_compensation",  # Default to 40,000 and user can change this value
         
         # HIDE THE TABLE BELOW THIS POINT - USER INPUTS ONLY ABOVE FOR `PCT` COLUMN #
         
         "cost_of_goods", # Rev - Gross Margin 
         "rent", # total_rent calculated in Rent()
         "depreciation", # total_depreciation calculated in Depreciation()
         "interest_expense", # total_interest calculated in Interest()
         "total_expense", # off_comp + salaries + rent + other_op_exp + depreciation
         "operating_income_loss", # Gross Margin -  Total Expense
         "pre_tax_profit" # operating income loss - Interest Expense + Other Income
         ),
  pct = c(22, 9, 10.88, 1, 0, 0, 0, 0, 0, 0, 0, 0),
  value = c(0, 0, 0, 0, 40000, 0, 0, 0, 0, 0, 0, 0)
)
```

```{r}
Depreciation_List <- Depreciation(scenario = "two", depreciation_table = depreciation)

Rent_List <- Rent(rent_table = rent)

Interest_List <- Interest(interest_table = interest)

Expense_Table <- Expense(expense_table = expenses, 
                        total_estimated_revenue = 1400000,
                        total_depreciation = Depreciation_List$total_depreciation, 
                        total_rent = Rent_List$total_rent,
                        total_interest = Interest_List$total_interest)

```

```{r}
Expense_Table # Expected Values
```

